version: "3.9"
services:
  #My application Image from Dockerhub Repository
  app:
    image: leereal/interview-challenge
    ports:
      - 8000:8000   
    depends_on:
      - app_db

  #MySQL Image
  app_db:
    image: mysql:5.7.22    
    environment:
      MYSQL_DATABASE: challenge
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root 
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports: 
      - 3306:3306